### ISSUE TITLE
WASM demos on Mac OS X

### ISSUE THREAD

**Issue by erlend-sh** [thebracket/rustrogueliketutorial#33] opened 2019-11-16 22:10 UTC
I'm getting this when I'm trying to run the demo:

<img width="771" alt="Screenshot 2019-11-16 at 14 49 09" src="https://user-images.githubusercontent.com/583842/68999803-3b520800-08c6-11ea-8656-37b2f357dadc.png">

**Comment by Zireael07** [comment] 2019-11-17 09:27
What OS and browser? On Ubuntu 18.04 LTS, Chrome 78.0.3904.97, it works.

**Comment by erlend-sh** [comment] 2019-11-17 16:12
MacBook Pro 2019, Firefox. Can’t get the exact version right now.

**Comment by thebracket** [comment] 2019-11-18 13:49
Does the example run if I you use an HTTPS link? I added SSL to the host a while back, and have slacked on adding it to all of the links in the book (and whenever I point people at the tutorial).

https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-61-townportal/

**Comment by erlend-sh** [comment] 2019-11-18 15:25
Tried both http and https in latest Firefox, Chrome and Safari on MacBook Pro, Catalina v10.15.1

2,3 GHz Dual-Core Intel Core i5
Intel Iris Plus Graphics 640 1536 MB

All I get is this black screen. It's probably not related to the "connection not secure" warning then so feel free to change the title. I checked on a different, older MacBook and couldn't get it to work there either. Has anyone with a macOS machine gotten it working?

**Comment by thebracket** [comment] 2019-11-18 15:34
I'll see if I can borrow my wife's Macbook this evening to give it a look. Hopefully, I didn't pick a GL mode that isn't happy on OS X!

**Comment by thebracket** [comment] 2019-11-19 13:33
I managed to get to use a Mac last night, and can confirm that this is an RLTK-level issue: the canvas opens, the WASM executes and logs keystrokes, but nothing gets rendered - just a black box.

I'll open an RLTK issue and link it to this one, and see about getting a library-level fix in ASAP.

**Comment by thebracket** [comment] 2019-11-20 20:21
I believe the issue is fixed in RLTK, pulling and rebuilding the tutorial now.

**Comment by thebracket** [comment] 2019-11-20 20:54
I'm happy to report that the demos are running on my virtual Mac:
![image](https://user-images.githubusercontent.com/14896751/69277269-9aa16800-0ba5-11ea-8ec4-1fb417942c59.png)

**Comment by thebracket** [comment] 2019-11-20 20:55
The RLTK changes ended up being very substantial; there's basically a whole new WebGL pipeline now. It's single-pass (or one pass per console layer), the post-process is integrated into the main loop, and it works by sampling dynamic textures rather than a giant vertex buffer - so it's really rather fast.

If anyone could confirm that they are working on a real Mac, I'd appreciate it!

**Comment by erlend-sh** [comment] 2019-11-21 10:15
Just confirmed it’s working, thanks so much for the quick turnaround! 👏 

Latest Firefox and Chrome both work. Safari does not, which I assume is because their WASM support remains incomplete.

**Comment by thebracket** [comment] 2019-11-21 13:36
I'll go ahead and close this out, then. Thanks! (I'm told that Safari support is a pipe-dream, due to lack of WebGL 2 support - so I won't stress that one.)

**Closed by thebracket** 2019-11-21 13:36 UTC
Labels: awaiting confirmation, bug
